name: CI Example

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
    - run: sleep 30s
    - name: output test
      uses: matt-lewis-testing-org/reusable-actions/.github/actions/test-action@cb79f4bbdd89c590967d2299e0a6b4da84e585b6
