name: CI Example

on:
  workflow_dispatch:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
    - name: output test
      uses: matt-lewis-testing-org/reusable-actions/.github/actions/example-action@c2d164c1de194dcbfdc7a9332218ce3024bddd54
    - name: example test
      uses: matt-lewis-testing-org/reusable-actions/.github/actions/test-action@674f1539c562e17741156da45ff2ab31b20b886a
