name: CI Example

on:
  workflow_dispatch:
  push:
    branches:
      - 'test-**'

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
    - name: output test
      uses: matt-lewis-testing-org/reusable-actions/.github/actions/example-action@674f1539c562e17741156da45ff2ab31b20b886a
    - name: example test
      uses: matt-lewis-testing-org/reusable-actions/.github/actions/test-action@674f1539c562e17741156da45ff2ab31b20b886a
