name: example workflow

on:
  workflow_call:

jobs:
  call-action-test:
    runs-on: ubuntu-latest
    steps:
    - name: output test
      uses: matt-lewis-testing-org/reusable-actions/.github/actions/test-action@08e4c3d697ba8d74fe7f591511ae4dff63f4c63f
