name: Stale PRs
on:
  workflow_dispatch:
  
jobs:
  handle_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Checkout SSO Broker Repo
        uses: actions/checkout@v4
        with:
            repository: matt-lewis-testing-org/approve-and-merge
            path: ./approve-and-merge
            token: ${{ secrets.LEWISM20_GH_TOKEN }}
            ref: random-stuff
            # submodules: true 
