name: update actions

on:
  workflow_dispatch:
    inputs:
      gh_token:
        required: true
        description: a github app token with write permissions to workflow

permissions:
  contents: write
  actions: write

jobs:
  update-actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.gh_token }}

    - name: Randomize Branch
      run: |
        random_number="$((RANDOM % 99999))"
        branch_name="update_actions_${random_number}"

        echo "BRANCH_NAME=$branch_name" >> "$GITHUB_ENV"

    - name: Create Branch
      run: |
        git fetch
        git checkout -b ${{ env.BRANCH_NAME }}
        git branch --set-upstream-to=origin/${{ env.BRANCH_NAME }} ${{ env.BRANCH_NAME }} || exit 0
        git pull -ff

        git branch
        git rev-parse --abbrev-ref HEAD
    
    - name: get initial info
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
      run: |
        SHA=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/matt-lewis-testing-org/reusable-actions/commits | jq 'first(.[].sha)' | tr -d '"')
        # Replace above org

        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/matt-lewis-testing-org/reusable-actions/commits/$SHA > response.json 
        # Replace above org

        ACTIONS=$(jq -r '.files[].filename' response.json | grep '.github/actions/.*/action.yml$' | awk -F'/' '{print $3}' | paste -sd "," -)

        # Clean up
        rm response.json
        
        echo "SHA: $SHA"
        echo "Actions List: $ACTIONS"
        
        echo "ACTIONS=$ACTIONS" >> "$GITHUB_ENV"
        echo "UPDATED_SHA=$SHA" >> "$GITHUB_ENV"

    - name: update actions
      id: update-actions
      if: env.ACTIONS != ''
      run: |
        updated_sha=${{ env.UPDATED_SHA }}

        ACTIONS_LIST=$(echo "${{ env.ACTIONS }}" | tr ',' '\n')
        changes_summary="## Updated Actions"
        
        for action_name in $ACTIONS_LIST; do
          search_dir="./.github/workflows"
          search_string="matt-lewis-testing-org/reusable-actions/.github/actions/$action_name@"
          # Replace above org

          file_list=$(grep -rl "$search_string" "$search_dir") || file_list=""

          if [ ! -z "$file_list" ]; then
            changes_summary="${changes_summary}\n- **$action_name:"
            for file in $file_list; do
              sed -i "s|${search_string}[[:space:]]*.*|${search_string}${updated_sha}|" "$file"
              cat "$file"
              changes_summary="${changes_summary}\n  - $file"
            done
            echo "ACTION_PRESENT=true" >> "$GITHUB_ENV"
          else
            echo "Action not used in any workflows."
            echo "ACTION_PRESENT=false" >> "$GITHUB_ENV"
          fi
        done

        # Escape newlines for GitHub Actions
        echo "CHANGES_SUMMARY<<EOF" >> "$GITHUB_ENV"
        echo -e "$changes_summary" >> "$GITHUB_ENV"
        echo "EOF" >> "$GITHUB_ENV"
      
    - name: Commit changes and commit PR
      if: env.ACTION_PRESENT != 'false' && env.ACTIONS != ''
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
      run: |
        git config user.name "Updating GitHub Actions"
        git config user.email "<>"
        git commit -am "Updated Actions to newest SHA" || exit 0
        git push --set-upstream origin ${{ env.BRANCH_NAME }}

        pr_url=$(gh pr create \
        -B main \
        -H ${{ env.BRANCH_NAME }} \
        --title "Update of GitHub Actions SHA" \
        --body "${{ env.CHANGES_SUMMARY }}") || exit 0

        echo "PR_URL=${pr_url}" >> "$GITHUB_ENV"

    - name: Message if no actions were changed
      if: env.ACTIONS == ''
      run: |
        echo "List of actions needing to be changed is empty, no files updated."
