name: update actions

on:
  workflow_dispatch:

jobs:
  update-actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.LEWISM20_GH_TOKEN }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.LEWISM20_GH_TOKEN }}
