name: update actions

on:
  workflow_dispatch:

jobs:
  update-actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.LEWISM20_GH_TOKEN }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@70836b4e54a00bab1eee59184cbc74803b72d98f
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.LEWISM20_GH_TOKEN }}
          update_version_with: 'default-branch-sha'
