name: update actions

on:
  workflow_dispatch:
    inputs:
      gh_token:
        required: true
        description: a github app token with write permissions to workflow

jobs:
  update-actions:
    runs-on: ubuntu-latest
    steps:
    - name: get initial info
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
      run: |
        SHA=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/matt-lewis-testing-org/reusable-actions/commits | jq 'first(.[].sha)' | tr -d '"')
        # Replace above org

        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/matt-lewis-testing-org/reusable-actions/commits/$SHA > response.json 
        # Replace above org

        ACTIONS=$(jq -r '.files[].filename' response.json | grep '.github/actions/.*/action.yml$' | awk -F'/' '{print $3}')

        echo "ACTIONS_LIST=$ACTIONS" >> "$GITHUB_ENV"
        echo "UPDATED_SHA=$SHA" >> "$GITHUB_ENV"

    - name: update actions
      id: update-actions
      run: |
        for action_name in ${{ env.ACTIONS_LIST }}; do
          search_dir=".github/workflows"
          search_string="matt-lewis-testing-org/reusable-actions/.github/actions/$action_name@"
          # Replace above org

          file_list=$(grep -rl "$search_string" "$search_dir")

          echo "Action name: $action_name"
          for file in $file_list; do
            echo "File that contains $action_name action: $file"
          done
        done
    
    - name: testing action change
      run: |
        cat 
